<?php 
$db['goods_marketable_application'] = array(
    'columns' => array(
        'apply_id' => array(
            'type' => 'bigint unsigned',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
        ),
        'goods_id' => array(
            'type' => 'table:goods',
            'width' => 150,
            'comment' => app::get('b2c')->_('商品id'),
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
        ),
        'status' => array(
            'type' => array(
                '0'=>'待审核',
                '1'=>'审核通过',
                '2'=>'审核不通过',
            ),
            'default' => '0',
            'label' => app::get('b2c')->_('申请状态'),
            'width' => 150,
            'editable' => true,
            'in_list' => true,
        ),
        'supply' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'label' => app::get('b2c')->_('允许申请'),
            'in_list' => false,
        ),
        'content' => array(
            'type' => 'varchar(255)',
            'label' => '申请内容',
            'width' => 110,
            'hidden' => false,
            'editable' => false,
        ),
        'restore' => array(
            'type' => 'varchar(255)',
            'label' => '回复内容',
            'width' => 110,
            'hidden' => false,
            'editable' => false,
        ),
        'apply_time' => array (
            'type' => 'time',
            'label' => '申请时间',
            'width' => 110,
            'editable' => false,
            'in_list' => true,
            'orderby' => true,
        ),
        'apply_user' => array (
            'type' => 'varchar(50)',
            'label' => '申请者',
            'required' => true,
            'default' => '',
            'editable' => false,
            'in_list' => true,
        ),
        'audit_time' => array (
            'type' => 'time',
            'label' => '审核时间',
            'width' => 110,
            'editable' => false,
            'in_list' => true,
            'orderby' => true,
        ),
        'audit_user' => array (
            'type' => 'varchar(50)',
            'label' => '审核者',
            'required' => true,
            'default' => '',
            'editable' => false,
            'in_list' => true,
        ),
        'last_modify' => array (
            'type' => 'last_modify',
            'label' => '更新时间',
            'width' => 110,
            'editable' => false,
            'in_list' => true,
            'orderby' => true,
        ),
        'disabled' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'in_list' => false,
        ),
    ),
);